steps:
- id: 'tf plan'
  name: 'hashicorp/terraform:1.0.0'
  entrypoint: 'sh'
  args:
  - '-c'
  - |
      echo "branch $BRANCH_NAME"
      if [ ! -z "$BRANCH_NAME" -a -d "cloudblog-terraform-config/environments/$BRANCH_NAME/" ]; then
        cd cloudblog-terraform-config/environments/$BRANCH_NAME
        echo "run init"
        terraform init
        echo "run validate"
        terraform validate
        echo "run plan"
        terraform plan -out terraform.plan
        terraform apply -auto-approve terraform.plan
      else
        for dir in cloudblog-terraform-config/environments/*/
        do
          cd ${dir}
          env=${dir%*/}
          env=${env#*/}
          echo ""
          echo "*************** TERRAFOM PLAN ******************"
          echo "******* At environment: ${env} ********"
          echo "*************************************************"
          terraform init
          terraform validate
          terraform plan || exit 1
          cd ../../
        done
      fi
steps:
...
- name: Run Tests
  env: 
    SECRET_KEY: ${{ secrets.SECRET_KEY }}
  run: |
    python manage.py test

- name: "gcr.io/cloud-builders/gcloud"
  args: ["app", "deploy"]
  timeout: "1600s"

