# Generated by Django 4.0.6 on 2022-08-28 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='url',
        ),
    ]
